[project]
name = "scp-python-deps"
version = "0.6.0"
description = "Python dependencies for SCP R package"
requires-python = ">=3.10,<3.13"

dependencies = [
    "numpy>=1.24.0,<2.0.0",
    "pandas>=2.0.0",
    "scipy>=1.10.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "scikit-learn>=1.3.0",
    "h5py>=3.8.0",
    "numba>=0.57.0",
    "anndata>=0.10.0",
]

[project.optional-dependencies]
# Velocity analysis dependencies
velocity = [
    "scvelo>=0.3.0",
    "scanpy>=1.9.0",
    "loompy>=3.0.0",
]

# Trajectory analysis dependencies
trajectory = [
    "scanpy>=1.9.0",
    "paga>=0.1.0",
    "phate>=1.0.0",
]

# Deep learning dependencies
deeplearning = [
    "scvi-tools>=1.0.0",
    "torch>=2.0.0",
]

# Apple Silicon optimizations
apple_silicon = [
    "scvi-tools[metal]>=1.0.0",
]

# Single-cell specific tools
singlecell = [
    "scikit-misc==0.1.4",
    "pynndescent>=0.5.10",
    "umap-learn>=0.5.3",
    "pymde>=0.1.18",
    "opentsne>=0.6.2",
    "scanorama>=1.7.3",
    "bbknn>=1.6.0",
    "leidenalg>=0.10.0",
    "louvain>=0.8.0",
    "scrublet>=0.2.3",
    "pybind11>=2.11.0",
]

# Machine learning
ml = [
    "xgboost>=2.0.0",
]

# All dependencies combined
all = [
    "scvelo>=0.3.0",
    "scanpy>=1.9.0",
    "loompy>=3.0.0",
    "paga>=0.1.0",
    "phate>=1.0.0",
    "scvi-tools>=1.0.0",
    "torch>=2.0.0",
    "scikit-misc==0.1.4",
    "pynndescent>=0.5.10",
    "umap-learn>=0.5.3",
    "pymde>=0.1.18",
    "opentsne>=0.6.2",
    "scanorama>=1.7.3",
    "bbknn>=1.6.0",
    "leidenalg>=0.10.0",
    "louvain>=0.8.0",
    "scrublet>=0.2.3",
    "pybind11>=2.11.0",
    "xgboost>=2.0.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"